apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-certificate
  namespace: demo-api
spec:
  secretName: secret-name-tls
  issuerRef:
    name: kube-issuer
    kind: ClusterIssuer
  commonName: jussun.com
  dnsNames:
    - $(DOMAIN_NAME)
    - www.jussun.com
