apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-certificate
  namespace: demo-api
spec:
  secretName: secret-name-tls
  issuerRef:
    name: kube-issuer
    kind: ClusterIssuer
  commonName: $(CERT_COMMON_NAME)
  dnsNames:
    - $(CERT_DNS_NAME_1)
    - $(CERT_DNS_NAME_2)
