apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-certificate
  namespace: demo-api
spec:
  secretName: secret-name-tls
  issuerRef:
    name: kube-issuer
    kind: ClusterIssuer
  commonName: jussun.com
  # commonName: { { .Values.certificate.replicas } }

  dnsNames:
    - jussun.com
    - www.jussun.com

    # commonName: { { .Values.certificate.commonName } }
    # dnsNames:
    # - { { .Values.certificate.dnsNames1 } }
    # - { { .Values.certificate.dnsNames2 } }
    - jussun.com
    - www.jussun.com
