apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: dev
  labels:
    app: demo-api
spec:
  selector:
    matchLabels:
      app: demo-api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: demo-api
          image: ghcr.io/champalab/demo-api:e3d7012603aa032b5a45ad7f37a000b946deeab2
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
         
          ports:
            - containerPort: 3000
              name: demo-api
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            # - name: vol-dummy
            #   mountPath: /app/uploads
            #   subPath: demo-api/uploads
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: vol-dummy
          nfs:

      restartPolicy: Always
