apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-dummy
  namespace: dev
  labels:
    app: node-dummy
spec:
  selector:
    matchLabels:
      app: node-dummy
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-dummy
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: node-dummy
          image: ghcr.io/champalab/node-dummy:5afb2758a6c80154959c3942f7152b607f71d976
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          livenessProbe:
            tcpSocket:
              port: 4500
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 4500
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          # env:
          #   - name: DB_HOST
          #     valueFrom:
          #       configMapKeyRef:
          #         name: node-dummy
          #         key: DB_HOST
          # envFrom:
          #   - configMapRef:
          #       name: node-dummy-config
          ports:
            - containerPort: 4500
              name: node-dummy
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: vol-dummy
              mountPath: /app/uploads
              subPath: node-dummy/uploads
      # hostAliases:
      #   - ip: 10.2.100.197
      #     hostnames:
      #       - mxf.laoevisa.gov.la
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: vol-dummy
        # _type: nfs
          nfs:
            # path: /srv/nfs/share
            # server: 195.35.23.213

      restartPolicy: Always
