name: Dev environment CI and CD

on:
  push:
    branches: ["main"]

jobs:
  # ==============
  # CI task
  # ==============
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Login ghcr.io
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.WORKFLOW_TOKEN }}
          logout: true
      - name: Pull the latest Docker image
        run: docker pull ghcr.io/champalab/node-dummy:latest || true
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/champalab/node-dummy:${{ env.GITHUB_SHA }} --tag ghcr.io/champalab/node-dummy:latest
      - name: Push the Docker image
        run: docker push ghcr.io/champalab/node-dummy:${{ env.GITHUB_SHA }}
      - name: Push the Docker image latest
        run: docker push ghcr.io/champalab/node-dummy:latest

  # ==============
  # CD DEV task
  # ==============
  gitops-dev-versioning:
    runs-on: ubuntu-latest
    needs: [build-and-push-docker-image]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: config git
        run: |
          git --version
          git config user.name "robot"
          git config user.email "root@laogw.link"
      - name: change image tag to deploy dev
        run: |
          sed "s|image: ghcr\.io/champalab/node-dummy:[^ ]*|image: ghcr.io/champalab/node-dummy:${GITHUB_SHA}|" infra/gitops/dev/deployment.yaml > tmp_deployment.yaml
          mv tmp_deployment.yaml infra/gitops/dev/deployment.yaml
          git add infra/gitops/dev/deployment.yaml
          git commit -m "[skip actions] 🤖 change dev docker image version to ${GITHUB_SHA}"
          git pull origin main --rebase
          git push
